package dreaming

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/alexherrero/agentm/daemon/internal/note"
	"github.com/alexherrero/agentm/daemon/internal/rules"
)

// The first job the binary carries: the lifecycle axis's automatic lane.
//
// A memory silent past `dormant_after_days` sinks to `dormant` in place. A
// dormant memory a genuine recall touched lifts back to `active`. A dormant
// memory past `archive_after_days` is **moved** to `archive/memory/<class>/`
// and stamped `archived`. An archived memory past `forget_after_days` is
// deleted, with a manifest and a journal line written first. An archived note
// the operator moves back into its class returns to `active` with its clock
// reset.
//
// **Archive used to be a candidate list this job never acted on, and deletion
// was not on the axis at all.** Session 5 reversed both: a stage nobody
// confirms is a stage that never happens, and the folders the machinery may
// touch are named. What the reversal buys is the eyeline the field never gave
// — the class folders hold what is alive, and one folder holds what is not.
// Obsidian resolves a link by basename, so a moved note is still found by every
// link that named it.
//
// The machinery moves a note's state only in the three observational classes.
// `entities/`, `mocs/` and `crystallized/` are walked and counted and never
// acted on: the first two are regenerated by their own pass, and a crystallized
// lesson is what the curve exists to preserve. `pinned` never moves;
// `type: preference` and `type: convention` decay but never sink, because a
// rule nobody has needed in a year is still the rule. A trace runs the shorter
// line `lifecycle_overrides.episodic` sets.
//
// Same words, same edit: the frontmatter change is a byte-exact port of the
// Python `set_lifecycle_text`, and every applied transition is appended to
// the same lifecycle journal the digest and scorecard read, so the two
// layers are one record while they overlap.

const (
	JobLifecycle        = "lifecycle"
	DefaultDormantAfter = 365.0
	DefaultArchiveAfter = 1825.0
	// DefaultForgetAfter is 730 days past the archive move — seven years from
	// the last time anything recalled the note.
	DefaultForgetAfter = 2555.0
	PreviewFraction    = 0.9
	// DefaultDemotionCap is what one pass may move when the contract names no
	// cap. The Go default was 200 and the Python cap it replaced was 25; the
	// contract's `demotion_cap` is 25, and a backlog drains over nights rather
	// than in one pass so a wrong threshold is visible in the morning note
	// before it has moved the whole corpus.
	DefaultDemotionCap    = 200
	LifecycleJournalName  = "lifecycle-journal.jsonl"
	lifecycleDefaultState = "active"
	lifecycleKeyDormant   = "dormant_after_days"
	lifecycleKeyArchive   = "archive_after_days"
	lifecycleKeyForget    = "forget_after_days"
	lifecycleKeyCap       = "demotion_cap"
	// ArchiveDir is where an archived memory goes, mirroring the memory tree:
	// `<memory root>/archive/memory/<class>/<slug>.md`.
	ArchiveDir = "archive"
	// ForwardDays is how far ahead the morning note's two forward lists look.
	ForwardDays = 30.0
)

var classDirs = []string{"semantic", "procedural", "episodic", "entities", "crystallized", "mocs"}

// observationalClasses are the three the machinery may move a note's state in.
// The other three are derived or permanent: `entities/` and `mocs/` are rebuilt
// by their own pass, and a crystallized lesson is the thing the curve exists to
// preserve.
var observationalClasses = map[string]bool{"semantic": true, "procedural": true, "episodic": true}

// neverSinkTypes decay like everything else and never sink. A rule that has not
// come up in a year is still the rule; it moves by supersession or the
// operator's edit, not by silence.
var neverSinkTypes = map[string]bool{"preference": true, "convention": true}

var typeRe = regexp.MustCompile(`(?m)^type:[ \t]*(\S+)`)
var sinceRe = regexp.MustCompile(`(?m)^lifecycle_since:[ \t]*"?'?(\d{4}-\d{2}-\d{2})`)

var slugRe = regexp.MustCompile(`(?m)^slug:[ \t]*(\S+)`)

// LifecyclePlan is what one pass would (or did) do.
type LifecyclePlan struct {
	Intents  []Intent `json:"-"`
	Demoted  []Move   `json:"demoted"`
	Revived  []Move   `json:"revived"`
	Archived []Move   `json:"archived"`
	Deleted  []Move   `json:"deleted"`
	// Returned is an archived note the operator moved back into its class. The
	// night follows the move rather than undoing it: nothing the operator moves
	// is moved back.
	Returned []Move `json:"returned"`
	// Candidates and Previews are what the confirm-gated arrangement produced
	// before the job moved anything itself. Kept because the morning note and
	// the scorecard read them, and because a note the cap held back is a
	// candidate that did not move tonight.
	Candidates []Move `json:"archive_candidates"`
	Previews   []Move `json:"previews"`
	// Touched is a note whose `lifecycle` the operator edited by hand since the
	// journal last recorded it. Named and left alone for the night.
	Touched []Move `json:"touched_by_hand"`
	// The two forward lists the morning note carries, each omitted when empty:
	// what sinks within thirty days, and what is archived within thirty days.
	// Computed here because this is the pass that knows every note's age.
	SinkingSoon   []Move `json:"sinking_within_30_days"`
	ArchivingSoon []Move `json:"archiving_within_30_days"`
	Capped        int    `json:"skipped_by_cap"`
	Considered    int    `json:"considered"`
}

// Move names one note and how long it has been silent.
type Move struct {
	Rel  string  `json:"rel"`
	Days float64 `json:"days"`
}

// Thresholds reads the contract's lifecycle lines for a note of no particular
// class, with the packaged defaults for a contract that predates them. A nil
// contract is the defaults.
func Thresholds(r *rules.Rules) (dormantAfter, archiveAfter float64) {
	d, a, _ := ThresholdsFor(r, "")
	return d, a
}

// ThresholdsFor reads the three lifecycle lines for one class: the class's own
// `lifecycle_overrides` where the contract names them, else the shared
// `thresholds`, else the packaged defaults.
//
// A class is a line of its own because a session trace is not a card. A trace
// is a handoff record and the raw material promote and crystallize read, and
// both have read it inside a quarter — so it runs 90 · 365 · 1,095 rather than
// 365 · 1,825 · 2,555, and that is the contract's to say, not this file's.
func ThresholdsFor(r *rules.Rules, class string) (dormantAfter, archiveAfter, forgetAfter float64) {
	dormantAfter, archiveAfter, forgetAfter = DefaultDormantAfter, DefaultArchiveAfter, DefaultForgetAfter
	if r == nil {
		return
	}
	read := func(key string, into *float64) {
		if v, ok := r.LifecycleThreshold(class, key); ok && v > 0 {
			*into = v
		}
	}
	read(lifecycleKeyDormant, &dormantAfter)
	read(lifecycleKeyArchive, &archiveAfter)
	read(lifecycleKeyForget, &forgetAfter)
	return
}

// DemotionCap is how many notes one pass may move along the axis, from the
// contract's `demotion_cap`. The flag wins when it names one, so a supervised
// run can hold a first night to a handful.
func DemotionCap(r *rules.Rules, flag int) int {
	if flag > 0 {
		return flag
	}
	if r != nil {
		if v, ok := r.Threshold(lifecycleKeyCap); ok && v > 0 {
			return int(v)
		}
	}
	return DefaultDemotionCap
}

// ClassOf reads the memory class out of a memory-root-relative path:
// `memory/<class>/…` and `archive/memory/<class>/…` alike.
func ClassOf(rel string) string {
	parts := strings.Split(rel, "/")
	for i, seg := range parts {
		if seg == "memory" && i+1 < len(parts)-1 {
			return parts[i+1]
		}
	}
	return ""
}

// InArchive reports whether a memory-root-relative path sits in the memory
// archive.
func InArchive(rel string) bool {
	return strings.HasPrefix(rel, ArchiveDir+"/")
}

// ArchiveDestination is where an archived note goes: the memory tree mirrored
// under `archive/`, so `memory/semantic/a.md` becomes
// `archive/memory/semantic/a.md`.
func ArchiveDestination(rel string) string {
	return ArchiveDir + "/" + rel
}

// ClassDestination is the reverse: where an archived note came from. Used to
// read an operator's own move back into the class, not to make one.
func ClassDestination(rel string) string {
	return strings.TrimPrefix(rel, ArchiveDir+"/")
}

// MemoryNotes lists the memory-class notes under `root` (the memory root,
// the directory holding memory/), as paths relative to it, sorted.
//
// The archive is walked with the classes, because what is in it is still the
// job's business: an archived note has a deletion line ahead of it, and a note
// the operator moved back out of it has to be seen to be returned to `active`.
func MemoryNotes(root string) ([]string, error) {
	var out []string
	for _, base := range []string{"", ArchiveDir} {
		found, err := memoryNotesUnder(root, base)
		if err != nil {
			return nil, err
		}
		out = append(out, found...)
	}
	sort.Strings(out)
	return out, nil
}

func memoryNotesUnder(root, base string) ([]string, error) {
	var out []string
	for _, cls := range classDirs {
		dir := filepath.Join(root, filepath.FromSlash(base), "memory", cls)
		if st, err := os.Stat(dir); err != nil || !st.IsDir() {
			continue
		}
		err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
			if err != nil {
				return nil
			}
			if d.IsDir() || filepath.Ext(p) != ".md" || d.Name() == "_index.md" || note.SyncArtifact(d.Name()) {
				return nil
			}
			rel, err := filepath.Rel(root, p)
			if err != nil {
				return nil
			}
			out = append(out, filepath.ToSlash(rel))
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return out, nil
}

// LifecycleOf reads a note's state; `active` when it carries none.
func LifecycleOf(n note.Note) string {
	if n.Lifecycle == "" {
		return lifecycleDefaultState
	}
	return n.Lifecycle
}

// SetLifecycle is the byte-exact port of lifecycle_transitions.set_lifecycle_text:
// the note with `lifecycle: <to>` and `lifecycle_since: <since>` — a
// line-surgical edit of the frontmatter, the body byte-identical, a note
// without frontmatter returned unchanged.
func SetLifecycle(text, to, since string) string {
	if !strings.HasPrefix(text, "---\n") {
		return text
	}
	lines := strings.Split(text, "\n")
	end := -1
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			end = i
			break
		}
	}
	if end < 0 {
		return text
	}
	seen := map[string]int{}
	for i := 1; i < end; i++ {
		k, _, ok := strings.Cut(lines[i], ":")
		if ok && len(lines[i]) > 0 && !strings.ContainsRune(" \t#-", rune(lines[i][0])) {
			key := strings.TrimSpace(k)
			if _, dup := seen[key]; !dup {
				seen[key] = i
			}
		}
	}
	var at int
	if i, ok := seen["lifecycle"]; ok {
		lines[i] = "lifecycle: " + to
		at = i + 1
	} else {
		lines = append(lines[:end], append([]string{"lifecycle: " + to}, lines[end:]...)...)
		at = end + 1
	}
	if i, ok := seen["lifecycle_since"]; ok {
		// A frontmatter key sits before the closing fence, so the insertion
		// above (at `end`) never shifts it.
		lines[i] = "lifecycle_since: " + since
	} else {
		lines = append(lines[:at], append([]string{"lifecycle_since: " + since}, lines[at:]...)...)
	}
	return strings.Join(lines, "\n")
}

// PlanLifecycle reads every memory under `root` and decides the pass. It
// writes nothing; the run applies the intents through the journal.
//
// `sidecarDir` is the engine state directory the recall-access sidecar lives
// in since the memory-root trims; the memory root is read as the fallback, so
// an empty sidecarDir means the legacy location alone.
func PlanLifecycle(root, sidecarDir string, r *rules.Rules, now time.Time, cap int) (LifecyclePlan, error) {
	var plan LifecyclePlan
	cap = DemotionCap(r, cap)
	rels, err := MemoryNotes(root)
	if err != nil {
		return plan, err
	}
	log := note.NewAccessLog(sidecarDir, root)
	// What the journal last recorded, so the pass can tell its own last move
	// from the operator's hand.
	lastJournaled := LastJournaledStates(sidecarDir)
	since := now.UTC().Format("2006-01-02")
	// Silence is counted in whole days from midnight, the way the Python
	// policy counts it (its anchors and its `now` are dates), so the two
	// layers agree on the figure and not just on the decision.
	dayNow := time.Date(now.UTC().Year(), now.UTC().Month(), now.UTC().Day(), 0, 0, 0, 0, time.UTC)
	for _, rel := range rels {
		p := filepath.Join(root, filepath.FromSlash(rel))
		raw, err := os.ReadFile(p)
		if err != nil {
			continue
		}
		st, err := os.Stat(p)
		if err != nil {
			continue
		}
		text := string(raw)
		n := note.Parse(rel, text, st.ModTime())
		plan.Considered++
		state := LifecycleOf(n)
		class := ClassOf(rel)
		dormantAfter, archiveAfter, forgetAfter := ThresholdsFor(r, class)

		// An archived note the operator moved back into its class. The night
		// follows the move rather than undoing it — nothing the operator moves
		// is moved back — so the note returns to `active` with its clock reset,
		// which is what putting it back said.
		if state == "archived" && !InArchive(rel) && observationalClasses[class] {
			if len(plan.Returned) >= cap {
				plan.Capped++
				continue
			}
			after := SetLifecycle(text, lifecycleDefaultState, since)
			summary := "moved back into its class by hand → active"
			plan.Intents = append(plan.Intents, Intent{Job: JobLifecycle, Rel: rel,
				Before: raw, After: []byte(after), Summary: summary,
				Meta: map[string]string{"from": state, "to": lifecycleDefaultState, "reason": summary}})
			plan.Returned = append(plan.Returned, Move{rel, 0})
			continue
		}
		// The operator's own edit of `lifecycle`, made in Obsidian rather than
		// through a lane that journals. It counts as a touch: the note is named
		// in tonight's report as theirs and left alone until the next pass, so
		// the night does not spend the same night arguing with an edit the
		// operator just made.
		if OperatorEdited(lastJournaled, rel, state) {
			plan.Touched = append(plan.Touched, Move{rel, 0})
			continue
		}
		if state == "pinned" || state == "superseded" {
			continue
		}
		if state == "archived" && !InArchive(rel) {
			// Archived, and in a class the machinery does not move. Left alone.
			continue
		}
		if note.IsDecayExempt(n.Flags) {
			continue
		}
		// Only the three observational classes move. `entities/` and `mocs/`
		// are rebuilt by their own pass and a crystallized lesson is what the
		// curve exists to preserve, so all three are counted and left.
		if !observationalClasses[class] {
			continue
		}
		noteType := ""
		if m := typeRe.FindStringSubmatch(text); m != nil {
			noteType = strings.Trim(m[1], `'"`)
		}
		slug := strings.TrimSuffix(filepath.Base(rel), ".md")
		if m := slugRe.FindStringSubmatch(text); m != nil {
			slug = strings.Trim(m[1], `'"`)
		}
		captured := ""
		if !n.Captured.IsZero() {
			captured = n.Captured.UTC().Format(time.RFC3339)
		}
		// The note's path is the clock's key; the slug rides along for a sidecar
		// still on version 1, where the basename is the only key there is.
		days, ok := note.ElapsedDays(log, rel, slug, n.Updated, n.Created, captured,
			n.CapturedSource, dayNow)
		if !ok {
			continue
		}
		switch {
		// The deletion, and it is the only thing in this job that removes a
		// file. Two clocks have to agree: the note has been silent past
		// `forget_after_days`, **and** it has been in the archive for the wait
		// between the two lines. Without the second, a note archived by hand
		// today — already years silent — would be deleted the same night.
		case state == "archived" && InArchive(rel) &&
			days > forgetAfter && archivedFor(text, dayNow) > forgetAfter-archiveAfter:
			if len(plan.Deleted) >= cap {
				plan.Capped++
				continue
			}
			summary := fmt.Sprintf("silent %.0f days, past %s %.0f → deleted", days, lifecycleKeyForget, forgetAfter)
			plan.Intents = append(plan.Intents, Intent{Job: JobLifecycle, Rel: rel,
				Before: raw, Delete: true, Summary: summary,
				Meta: map[string]string{"from": state, "to": "purged", "reason": summary}})
			plan.Deleted = append(plan.Deleted, Move{rel, days})
		case state == "archived":
			// In the archive and not yet due. Nothing to do, and nothing below
			// this applies to it.
		case state == lifecycleDefaultState && days > dormantAfter:
			if neverSinkTypes[noteType] {
				// It decays like everything else; it does not sink. A rule
				// nobody has needed in a year is still the rule.
				break
			}
			if len(plan.Demoted) >= cap {
				plan.Capped++
				continue
			}
			after := SetLifecycle(text, "dormant", since)
			summary := fmt.Sprintf("silent %.0f days, past %s %.0f → dormant", days, lifecycleKeyDormant, dormantAfter)
			plan.Intents = append(plan.Intents, Intent{Job: JobLifecycle, Rel: rel, Before: raw, After: []byte(after), Summary: summary,
				Meta: map[string]string{"from": state, "to": "dormant", "reason": summary}})
			plan.Demoted = append(plan.Demoted, Move{rel, days})
		case state == "dormant" && days <= dormantAfter:
			after := SetLifecycle(text, lifecycleDefaultState, since)
			summary := fmt.Sprintf("recalled %.0f days ago, within %s → active", days, lifecycleKeyDormant)
			plan.Intents = append(plan.Intents, Intent{Job: JobLifecycle, Rel: rel, Before: raw, After: []byte(after), Summary: summary,
				Meta: map[string]string{"from": state, "to": lifecycleDefaultState, "reason": summary}})
			plan.Revived = append(plan.Revived, Move{rel, days})
		// The archive move. It used to be a candidate list this job never acted
		// on; the note is moved now, to `archive/memory/<class>/`, and stamped.
		// The class folders hold what is alive and one folder holds what is not
		// — and Obsidian resolves a link by basename, so every link that named
		// the note still finds it.
		case state == "dormant" && days > archiveAfter:
			plan.Candidates = append(plan.Candidates, Move{rel, days})
			if len(plan.Archived) >= cap {
				plan.Capped++
				continue
			}
			after := SetLifecycle(text, "archived", since)
			dst := ArchiveDestination(rel)
			summary := fmt.Sprintf("silent %.0f days, past %s %.0f → archived", days, lifecycleKeyArchive, archiveAfter)
			plan.Intents = append(plan.Intents, Intent{Job: JobLifecycle, Rel: rel, To: dst,
				Before: raw, After: []byte(after), Summary: summary,
				Meta: map[string]string{"from": state, "to": "archived", "reason": summary}})
			plan.Archived = append(plan.Archived, Move{rel, days})
		case state == "dormant" && days > archiveAfter*PreviewFraction:
			plan.Previews = append(plan.Previews, Move{rel, days})
		}

		// The two forward lists the morning note carries. Read off the same
		// ages the decisions above were made from, so what the note says is
		// coming is what this pass would do next.
		switch {
		case state == lifecycleDefaultState && !neverSinkTypes[noteType] &&
			days <= dormantAfter && days > dormantAfter-ForwardDays:
			plan.SinkingSoon = append(plan.SinkingSoon, Move{rel, days})
		case state == "dormant" && days <= archiveAfter && days > archiveAfter-ForwardDays:
			plan.ArchivingSoon = append(plan.ArchivingSoon, Move{rel, days})
		}
	}
	return plan, nil
}

// archivedFor is how many days ago the note was stamped with the state it
// carries, from its own `lifecycle_since`. A note with no stamp reads as
// forever, which is the reading that lets a pre-stamp archive still be
// deletable rather than immortal.
func archivedFor(text string, now time.Time) float64 {
	m := sinceRe.FindStringSubmatch(text)
	if m == nil {
		return math.Inf(1)
	}
	t, err := time.Parse("2006-01-02", m[1])
	if err != nil {
		return math.Inf(1)
	}
	return now.Sub(t).Hours() / 24
}

// lifecycleLine is one line of the governance journal the Python layer
// keeps (lifecycle_transitions.journal_append): the same keys, in the same
// sorted order, so both layers write one record.
type lifecycleLine struct {
	Actor  string  `json:"actor"`
	From   string  `json:"from"`
	Reason string  `json:"reason"`
	Rel    string  `json:"rel"`
	RunID  *string `json:"run_id"`
	To     string  `json:"to"`
	TS     string  `json:"ts"`
}

// AppendLifecycleJournal records one applied transition in the governance
// journal under the engine state dir, as the Python policy would.
func AppendLifecycleJournal(engineStateDir, rel, from, to, reason, runID string, now time.Time) error {
	p := filepath.Join(engineStateDir, LifecycleJournalName)
	if err := os.MkdirAll(engineStateDir, 0o755); err != nil {
		return err
	}
	return appendLifecycleLine(p, rel, from, to, reason, runID, now)
}

// EnsureLifecycleJournal is AppendLifecycleJournal made idempotent: a line
// for the same run, note and state is written once, whichever of the pass
// and its resume gets there first.
func EnsureLifecycleJournal(engineStateDir, rel, from, to, reason, runID string, now time.Time) error {
	p := filepath.Join(engineStateDir, LifecycleJournalName)
	if blob, err := os.ReadFile(p); err == nil {
		for _, line := range strings.Split(string(blob), "\n") {
			var got lifecycleLine
			if json.Unmarshal([]byte(line), &got) != nil {
				continue
			}
			if got.Rel == rel && got.To == to && got.RunID != nil && *got.RunID == runID {
				return nil
			}
		}
	}
	if err := os.MkdirAll(engineStateDir, 0o755); err != nil {
		return err
	}
	return appendLifecycleLine(p, rel, from, to, reason, runID, now)
}

func appendLifecycleLine(p, rel, from, to, reason, runID string, now time.Time) error {
	line := lifecycleLine{Actor: "policy", From: from, Reason: reason, Rel: rel, To: to,
		TS: now.UTC().Format("2006-01-02T15:04:05+00:00")}
	if runID != "" {
		line.RunID = &runID
	}
	blob, err := json.Marshal(line)
	if err != nil {
		return err
	}
	f, err := os.OpenFile(p, os.O_APPEND|os.O_CREATE|os.O_RDWR, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	// A kill mid-append leaves a torn last line; healed first, as the
	// mutation journal does, so this line is not glued onto the fragment.
	if st, err := f.Stat(); err == nil && st.Size() > 0 {
		last := make([]byte, 1)
		if _, err := f.ReadAt(last, st.Size()-1); err == nil && last[0] != '\n' {
			if _, err := f.Write([]byte{'\n'}); err != nil {
				return err
			}
		}
	}
	if _, err := f.Write(append(blob, '\n')); err != nil {
		return err
	}
	return f.Sync()
}

// PurgeManifestDir is where the record of a deletion goes, beside the manifests
// every other purge in this vault has written: `diagnostics/migrations/purge/`
// under the memory root, one directory per run.
const PurgeManifestDir = "diagnostics/migrations/purge"

// DeletionRow is one line of the manifest: enough to know what was deleted and
// to find it again in the vault's git history.
type DeletionRow struct {
	Rel       string  `json:"rel"`
	Title     string  `json:"title"`
	Lifecycle string  `json:"lifecycle"`
	Since     string  `json:"since"`
	Days      float64 `json:"days"`
	SHA256    string  `json:"sha256"`
}

// WriteDeletionManifest records what a pass is about to delete, and returns the
// manifest's path.
//
// **Written before the files go, and the deletions are dropped if it cannot be
// written.** That ordering is the whole of what makes an automatic deletion
// defensible: the doctrine this reverses said no policy outcome ever deletes a
// memory, and what replaced it is not "the night may delete" but "every
// deletion has a manifest and a journal line first". A deletion with no record
// is the thing the old rule was protecting against, and it is still refused.
//
// The vault's git history holds the bytes; this holds the names, so the deep
// search has something to look for.
func WriteDeletionManifest(root, runID string, rows []DeletionRow, now time.Time) (string, error) {
	if len(rows) == 0 {
		return "", nil
	}
	dir := filepath.Join(root, filepath.FromSlash(PurgeManifestDir),
		now.UTC().Format("20060102T150405Z"))
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	manifest := map[string]any{
		"written":  now.UTC().Format(time.RFC3339),
		"run_id":   runID,
		"by":       "the night's lifecycle job",
		"criteria": "silent past the contract's forget_after_days, and archived for the wait between the archive and forget lines",
		"count":    len(rows),
		"rows":     rows,
	}
	blob, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return "", err
	}
	p := filepath.Join(dir, "manifest.json")
	if err := os.WriteFile(p, append(blob, '\n'), 0o644); err != nil {
		return "", err
	}
	return p, nil
}

// DeletionRows reads what the plan is about to delete, for the manifest.
func DeletionRows(root string, intents []Intent, deleted []Move) []DeletionRow {
	days := map[string]float64{}
	for _, m := range deleted {
		days[m.Rel] = m.Days
	}
	var out []DeletionRow
	for _, in := range intents {
		if !in.Delete || in.Job != JobLifecycle {
			continue
		}
		row := DeletionRow{Rel: in.Rel, Days: days[in.Rel], SHA256: Hash(in.Before)}
		n := note.Parse(in.Rel, string(in.Before), time.Time{})
		row.Title = strings.TrimSpace(n.Title)
		row.Lifecycle = n.Lifecycle
		if m := sinceRe.FindStringSubmatch(string(in.Before)); m != nil {
			row.Since = m[1]
		}
		out = append(out, row)
	}
	return out
}

// LastJournaledStates is the state the journal last recorded for each note,
// and who set it. The pass reads it to tell its own last move from the
// operator's hand.
func LastJournaledStates(engineStateDir string) map[string]lifecycleLine {
	out := map[string]lifecycleLine{}
	if engineStateDir == "" {
		return out
	}
	blob, err := os.ReadFile(filepath.Join(engineStateDir, LifecycleJournalName))
	if err != nil {
		return out
	}
	for _, raw := range strings.Split(string(blob), "\n") {
		raw = strings.TrimSpace(raw)
		if raw == "" {
			continue
		}
		var line lifecycleLine
		if err := json.Unmarshal([]byte(raw), &line); err != nil {
			continue
		}
		if line.Rel == "" {
			continue
		}
		out[line.Rel] = line
	}
	return out
}

// OperatorEdited reports whether a note's state was changed by someone other
// than this machinery since the journal last recorded it.
//
// The design's words: your edit of `lifecycle` in Obsidian is a touch. The
// night journals it as yours, stamps `lifecycle_since`, and does not re-sink
// the note that night — because re-sinking it would be the night arguing with
// the operator about a file they just edited, and nothing the operator moves or
// edits is moved or edited back.
//
// Only a note the journal has seen can answer this. A note the night has never
// moved has no recorded state to disagree with, and its own frontmatter is the
// only account of it there is.
func OperatorEdited(last map[string]lifecycleLine, rel, state string) bool {
	line, ok := last[rel]
	if !ok || line.To == "" {
		return false
	}
	if line.Actor != "policy" {
		// The operator's own lane already recorded it; nothing to notice.
		return false
	}
	return line.To != state
}
