#!/usr/bin/env python3
"""Recall is not run for prompts nobody typed.

The UserPromptSubmit hook fires on every record the host submits, not only the
ones a person wrote. Measured over 688 real injections in the operator's
transcripts, 233 (33.9%) were background-task notifications, system reminders,
or slash-command envelopes, and the notes recall pulled into context for them
came to 14,797,695 characters — roughly 3.7M tokens spent matching a vault
against `pass: 15 | skipping: 2`.

Two properties, and the second is the one that is easy to get wrong:

  1. **A machine-generated prompt runs no search at all.** Not a search that
     returns nothing — no daemon call, no corpus walk. `subprocess.run` and
     `query()` are both spied on, because "cheap enough" is not the claim; the
     claim is that the work does not happen.

  2. **Position is the test, not presence.** These markers are ordinary subject
     matter in a repo whose sessions are about its own hooks. In the same
     transcript sweep, 233 prompts carried a marker only mid-prompt and every
     one of them was a genuine information need — the sufficiency autorater's
     judge prompts, which quote real traffic verbatim, and the brief for this
     change, which quotes all six tags. A substring rule would have silently
     denied recall to exactly those.

The stderr contract is checked alongside: a skip must announce itself and name
which marker fired, so it reads as a decision rather than as a retrieval that
came back empty. That distinction is what GH #92 was made of, and
`scripts/health/recall_traffic.py` is pinned here to parse the line, since the
hook still writes an attachment on a skip and a reader that could not tell the
two apart would count skips as zero-hit recalls.

Expected strings are hand-written literals. The one place a module constant is
read is the coverage lock, which exists to fail when a marker is added without
a test — it compares the module's declared set against a hand-written list,
which is the opposite of recomputing an expectation from the implementation.

Run: python3 scripts/test_recall_machine_prompt_skip.py
"""
from __future__ import annotations

import io
import json
import subprocess
import sys
import tempfile
import unittest
import unittest.mock
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent
sys.path.insert(0, str(_REPO / "scripts" / "health"))
sys.path.insert(0, str(_REPO / "harness" / "skills" / "memory" / "scripts"))

import recall  # noqa: E402
import recall_traffic as rt  # noqa: E402


# Every marker, written out here rather than generated. The coverage lock at the
# bottom fails if the module grows one that this list does not name.
_TAG_PROMPTS: dict[str, str] = {
    "<task-notification>": (
        "<task-notification>Background task 'check-all' finished: "
        "pass: 15 | skipping: 2</task-notification>"
    ),
    "<system-reminder>": (
        "<system-reminder>Your todo list has changed. DO NOT mention this "
        "explicitly to the user.</system-reminder>"
    ),
    "<local-command-stdout>": (
        "<local-command-stdout>On branch main\nnothing to commit"
        "</local-command-stdout>"
    ),
    "<local-command-caveat>": (
        "<local-command-caveat>Caveat: The messages below were generated by "
        "the user while running local commands.</local-command-caveat>"
    ),
    "<command-name>": "<command-name>/clear</command-name>",
    "<command-message>": "<command-message>clear</command-message>",
    "<command-args>": "<command-args></command-args>",
}

_LITERAL_PROMPTS: dict[str, str] = {
    "[SYSTEM NOTIFICATION - NOT USER INPUT]": (
        "[SYSTEM NOTIFICATION - NOT USER INPUT]\n"
        "This is an automated background-task event, NOT a message from the "
        "user.\n\n<task-notification>done</task-notification>"
    ),
}


def _write(path: Path, body: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"---\nname: {path.stem}\nkind: fix\ntags: []\n---\n\n{body}\n",
        encoding="utf-8",
    )
    return path


def _payload(*paths: str) -> str:
    """A daemon `search -json` response naming `paths`, best-scored first."""
    return json.dumps({
        "results": [
            {"path": p, "score": 20.0 - i, "raw_score": 20.0 - i,
             "captured": "2026-08-10T04:13:43Z", "captured_source": "mtime",
             "snippet": "…"}
            for i, p in enumerate(paths)
        ],
        "matched": len(paths),
    })


class _SpyDaemon:
    """Stands in for `subprocess.run`, recording every argv it was handed."""

    def __init__(self, stdout: str = ""):
        self.stdout = stdout
        self.calls: list[list[str]] = []

    def __call__(self, argv, **kwargs):
        self.calls.append(list(argv))
        return subprocess.CompletedProcess(argv, 0, stdout=self.stdout, stderr="")


class _Fixture(unittest.TestCase):
    """A vault at `<root>/Agent`, matching the post-cutover layout."""

    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name) / "Vault"
        self.vault = self.root / "Agent"
        _write(self.vault / "memory" / "zorbulax.md", "The zorbulax subsystem.")

    def _submit(self, prompt: str, *, daemon_stdout: str = ""):
        """Run the hook path. Returns (rc, stdout, stderr, daemon, query_spy).

        Both engines are spied rather than stubbed away: the property is that
        neither is reached, and a stub that returned [] would pass a test that
        only looked at the output.
        """
        daemon = _SpyDaemon(stdout=daemon_stdout)
        query_spy = unittest.mock.Mock(return_value=[])
        out, err = io.StringIO(), io.StringIO()
        with unittest.mock.patch.object(recall.subprocess, "run", daemon), \
                unittest.mock.patch.object(recall, "query", query_spy):
            rc = recall.prompt_submit(
                vault=self.vault, prompt=prompt, stdout=out, stderr=err
            )
        return rc, out.getvalue(), err.getvalue(), daemon, query_spy


class AMachineGeneratedPromptRunsNoSearch(_Fixture):
    """Property 1 — no daemon call, no walk, nothing injected, exit 0."""

    def _assert_skipped(self, marker: str, prompt: str):
        rc, out, err, daemon, query_spy = self._submit(prompt)
        self.assertEqual(rc, 0, f"{marker}: the hook must never block a prompt")
        self.assertEqual(
            daemon.calls, [],
            f"{marker}: the daemon was queried for a prompt nobody typed",
        )
        self.assertEqual(
            query_spy.call_count, 0,
            f"{marker}: the in-process corpus walk ran for a prompt nobody typed",
        )
        self.assertEqual(out, "", f"{marker}: something was injected")
        self.assertIn("skipped:", err, f"{marker}: the skip was silent")
        self.assertIn(
            marker, err, f"{marker}: the skip did not name which marker fired"
        )
        self.assertIn("machine-generated", err)
        # The line must not be mistakable for a search that found nothing.
        self.assertNotIn("Loaded 0 relevant", err)

    def test_a_task_notification_is_skipped(self):
        self._assert_skipped("<task-notification>",
                             _TAG_PROMPTS["<task-notification>"])

    def test_a_system_reminder_is_skipped(self):
        self._assert_skipped("<system-reminder>",
                             _TAG_PROMPTS["<system-reminder>"])

    def test_local_command_stdout_is_skipped(self):
        self._assert_skipped("<local-command-stdout>",
                             _TAG_PROMPTS["<local-command-stdout>"])

    def test_the_local_command_caveat_is_skipped(self):
        """89 byte-identical copies of a 245-char boilerplate string, with
        nothing after the closing tag. Not a marker the brief named — it turned
        up in the traffic survey."""
        self._assert_skipped("<local-command-caveat>",
                             _TAG_PROMPTS["<local-command-caveat>"])

    def test_a_command_name_envelope_is_skipped(self):
        self._assert_skipped("<command-name>", _TAG_PROMPTS["<command-name>"])

    def test_a_command_message_envelope_is_skipped(self):
        self._assert_skipped("<command-message>",
                             _TAG_PROMPTS["<command-message>"])

    def test_a_command_args_envelope_is_skipped(self):
        self._assert_skipped("<command-args>", _TAG_PROMPTS["<command-args>"])

    def test_the_system_notification_banner_is_skipped(self):
        """A plain-text banner that prefixes a task-notification rather than
        leading with the tag, so the tag rule alone would serve it."""
        self._assert_skipped(
            "[SYSTEM NOTIFICATION - NOT USER INPUT]",
            _LITERAL_PROMPTS["[SYSTEM NOTIFICATION - NOT USER INPUT]"],
        )

    def test_a_leading_newline_does_not_defeat_the_match(self):
        self._assert_skipped(
            "<task-notification>",
            "\n\n  " + _TAG_PROMPTS["<task-notification>"],
        )

    def test_a_tag_carrying_attributes_is_still_matched(self):
        rc, _out, err, daemon, _spy = self._submit(
            '<task-notification id="7">done</task-notification>'
        )
        self.assertEqual(rc, 0)
        self.assertEqual(daemon.calls, [])
        self.assertIn("<task-notification>", err)

    def test_the_vault_is_never_touched(self):
        """The check is cheaper than the vault, and sits ahead of it. A skip
        that still walked `_always-load/` would pay most of the cost this
        change exists to avoid."""
        spy = unittest.mock.Mock(side_effect=AssertionError("vault was read"))
        with unittest.mock.patch.object(recall, "_collect_always_load_paths", spy):
            rc = recall.prompt_submit(
                vault=self.vault,
                prompt=_TAG_PROMPTS["<task-notification>"],
                stdout=io.StringIO(),
                stderr=io.StringIO(),
            )
        self.assertEqual(rc, 0)
        self.assertEqual(spy.call_count, 0)


class AHumanPromptQuotingAMarkerIsStillServed(_Fixture):
    """Property 2 — position is the test, not presence.

    Every prompt below is one a person actually typed, and each contains a
    marker somewhere other than the start. Recall must run for all of them.
    """

    def _assert_served(self, prompt: str):
        rc, out, err, daemon, _spy = self._submit(
            prompt, daemon_stdout=_payload("Agent/memory/zorbulax.md")
        )
        self.assertEqual(rc, 0)
        self.assertNotIn("skipped:", err, "a human prompt was silently skipped")
        self.assertEqual(len(daemon.calls), 1, "the daemon was never asked")
        self.assertIn("zorbulax", out, "nothing was injected for a real prompt")

    def test_a_marker_quoted_mid_sentence_is_served(self):
        """The shape the brief itself has: a prompt about the markers."""
        self._assert_served(
            "The markers are structural and easy to match at the top of the "
            "prompt text — <task-notification>, <system-reminder>, "
            "<local-command-stdout>, <command-name>/<command-message>/"
            "<command-args>. Skip recall when the prompt is machine-generated."
        )

    def test_the_autoraters_judge_prompt_is_served(self):
        """201 of the 233 mid-prompt hits in the sweep were this: the
        sufficiency judge quoting a real transcript prompt inside its own."""
        self._assert_served(
            "You are judging whether some retrieved context was enough.\n\n"
            "REQUEST:\n<task-notification>pass: 15 | skipping: 2"
            "</task-notification>\n\nAnswer one question."
        )

    def test_a_prompt_merely_beginning_with_a_less_than_sign_is_served(self):
        self._assert_served("<3 this refactor — does zorbulax still work?")

    def test_a_prompt_naming_a_marker_without_brackets_is_served(self):
        self._assert_served("why does task-notification traffic hit the vault?")

    def test_a_close_tag_at_the_start_is_not_a_marker(self):
        """An opening tag is the signal. A stray close tag is not one."""
        self._assert_served(
            "</task-notification> — what is this leftover doing in zorbulax?"
        )

    def test_a_similarly_named_tag_is_not_matched(self):
        self._assert_served(
            "<task-notification-format> is what I want to change in zorbulax."
        )


class AnEmptyPromptKeepsItsExistingBehavior(_Fixture):
    """Whitespace is not a marker. These prompts reached the engine before this
    change and must still reach it — a skip here would be a new behavior
    wearing this change's clothes."""

    def test_an_empty_prompt_is_not_treated_as_machine_generated(self):
        self.assertIsNone(recall._machine_prompt_marker(""))

    def test_a_whitespace_prompt_is_not_treated_as_machine_generated(self):
        self.assertIsNone(recall._machine_prompt_marker("   \n\t  "))

    def _assert_searched(self, prompt: str):
        """The engine runs and reports an ordinary empty recall.

        Not the daemon: it declines a contentless query on its own ("better to
        fall back than to search for the empty string" — see
        test_recall_daemon_fast_path.py), so the in-process walk is what
        "still searched" means for these two, exactly as before this change.
        """
        rc, _out, err, daemon, query_spy = self._submit(prompt)
        self.assertEqual(rc, 0)
        self.assertNotIn("skipped:", err)
        self.assertEqual(daemon.calls, [], "the daemon declines an empty query")
        self.assertEqual(query_spy.call_count, 1, "no search ran at all")
        self.assertIn("Loaded 0 relevant entries", err)

    def test_an_empty_prompt_still_reaches_the_engine(self):
        self._assert_searched("")

    def test_a_whitespace_prompt_still_reaches_the_engine(self):
        self._assert_searched("   \n  ")

    def test_a_none_prompt_keeps_its_own_distinct_line(self):
        """`None` means the payload had no `prompt` field at all. It already
        had a reason line, and it must not be relabelled as a skip."""
        err = io.StringIO()
        rc = recall.prompt_submit(
            vault=self.vault, prompt=None, stdout=io.StringIO(), stderr=err
        )
        self.assertEqual(rc, 0)
        self.assertIn("no prompt on stdin", err.getvalue())
        self.assertNotIn("machine-generated", err.getvalue())


class TheTrafficReaderCanTellASkipFromAnEmptyRecall(unittest.TestCase):
    """The hook still fires and still writes an attachment on a skip. Without a
    field for it, `recall_traffic.py` would file those as ordinary injections
    that loaded nothing — the exact "found nothing" versus "never searched"
    conflation the module exists to keep visible."""

    _SKIP_LINE = (
        "[memory-recall-prompt-submit] skipped: <task-notification> prompt is "
        "machine-generated, not an information need — no recall run"
    )
    _LOADED_LINE = (
        "[memory-recall-prompt-submit] Loaded 3 relevant entries: alpha, beta, "
        "gamma (engine: daemon, 68ms, scope=memory-root, terms: 'a b')"
    )

    def test_a_skip_line_parses_as_skipped_and_names_its_marker(self):
        got = rt.parse_stderr(self._SKIP_LINE)
        self.assertEqual(got.get("skipped"), "<task-notification>")
        self.assertNotIn("loaded", got)

    def test_a_real_recall_is_not_marked_skipped(self):
        got = rt.parse_stderr(self._LOADED_LINE)
        self.assertNotIn("skipped", got)
        self.assertEqual(got["loaded"], 3)

    def test_the_reader_matches_the_line_the_hook_actually_writes(self):
        """Not a hand-copied string: the line is produced by running the hook,
        so a reworded skip message fails here instead of silently unparsing
        every future row."""
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        vault = Path(tmp.name) / "Vault" / "Agent"
        _write(vault / "memory" / "zorbulax.md", "The zorbulax subsystem.")
        err = io.StringIO()
        recall.prompt_submit(
            vault=vault,
            prompt="<task-notification>pass: 15</task-notification>",
            stdout=io.StringIO(),
            stderr=err,
        )
        self.assertEqual(
            rt.parse_stderr(err.getvalue()).get("skipped"), "<task-notification>"
        )


class EveryDeclaredMarkerHasATest(unittest.TestCase):
    """A coverage lock, not a mirror. Adding a marker to the module without
    adding a case above fails here rather than shipping untested."""

    def test_the_tag_set_is_exactly_the_one_covered_here(self):
        self.assertEqual(
            sorted(recall._MACHINE_PROMPT_TAGS),
            sorted(m.strip("<>") for m in _TAG_PROMPTS),
        )

    def test_the_literal_set_is_exactly_the_one_covered_here(self):
        self.assertEqual(
            sorted(recall._MACHINE_PROMPT_LITERALS), sorted(_LITERAL_PROMPTS)
        )


if __name__ == "__main__":
    unittest.main(verbosity=2)
