#!/usr/bin/env bash
# structural_2a.sh — the vault-side moves of filing-v2 part 2a, in one
# scripted, resumable pass.
#
# The code in this commit already writes to the new locations; this script
# moves the existing content to meet it. Run order on the live machine:
# merge the PR, update the clone, quiesce the daemon + runner, run with
# --apply, kickstart, verify. Until --apply is passed it only prints what it
# would do — the dry run IS the default, per the migration invariants
# (basenames preserved; dry-run reviewed before apply; link-check green on
# both sides).
#
# Idempotent: every move checks its source exists and its destination
# doesn't; a re-run after a partial apply completes the remainder and
# touches nothing done.
set -euo pipefail

VAULT="${MEMORY_VAULT_PATH:-}"
if [[ -z "$VAULT" || ! -d "$VAULT" ]]; then
  echo "structural_2a: MEMORY_VAULT_PATH unset or not a directory" >&2
  exit 2
fi

APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1

moved=0; skipped=0
say() { echo "  $*"; }
run() {
  if [[ $APPLY -eq 1 ]]; then "$@"; else say "would: $*"; fi
}

move_into() { # move_into <src-file-or-glob-expanded path> <dest-dir>
  local src="$1" dest="$2"
  [[ -e "$src" ]] || { skipped=$((skipped+1)); return 0; }
  local base; base="$(basename "$src")"
  if [[ -e "$dest/$base" ]]; then
    say "skip (exists at destination): $base"
    skipped=$((skipped+1)); return 0
  fi
  run mv "$src" "$dest/$base"
  moved=$((moved+1))
}

echo "== task 2: diagnostics assembly =="
DIAG="$VAULT/diagnostics"
run mkdir -p "$DIAG/health" "$DIAG/dreaming" "$DIAG/digests"

OLD_DIAG="$VAULT/desk/diagnostics"
if [[ -d "$OLD_DIAG" ]]; then
  for f in "$OLD_DIAG"/*dreaming*; do move_into "$f" "$DIAG/dreaming"; done
  for f in "$OLD_DIAG"/*; do
    local_base="$(basename "$f")"
    [[ "$local_base" == "Icon"* ]] && continue   # Drive artifact, stays for the sync layer to manage
    [[ "$local_base" == *dreaming* ]] && continue # first loop's — keeps the dry run truthful
    move_into "$f" "$DIAG/health"
  done
  if [[ $APPLY -eq 1 ]]; then rmdir "$OLD_DIAG" 2>/dev/null || say "note: $OLD_DIAG not empty, left in place"; fi
fi

OLD_BRIEFS="$VAULT/desk/briefs"
if [[ -d "$OLD_BRIEFS" ]]; then
  for f in "$OLD_BRIEFS"/*; do
    [[ "$(basename "$f")" == "Icon"* ]] && continue
    move_into "$f" "$DIAG/digests"
  done
  if [[ $APPLY -eq 1 ]]; then rmdir "$OLD_BRIEFS" 2>/dev/null || say "note: $OLD_BRIEFS not empty, left in place"; fi
fi

MOC="$DIAG/moc-diagnostics.md"
if [[ ! -e "$MOC" && $APPLY -eq 1 ]]; then
  cat > "$MOC" <<'EOF'
---
title: moc-diagnostics
kind: moc
status: active
created: 2026-09-02
---

# Diagnostics

The system's health surfaces, one subdirectory per family. Regenerated by the
dreaming cadence once part 6 lands; seeded by the 2a migration until then.

- [[latest_health_scorecard]] — the corpus scorecard, in `health/`, dated
  copies beside it with the completeness and retrieval-gate verdicts.
- `dreaming/` — the dreaming scorecards: what the nightly pass did and spent.
- `digests/` — the daily digests and window-park notes the runner delivers.
EOF
  echo "  seeded $MOC"
elif [[ ! -e "$MOC" ]]; then
  say "would: seed $MOC"
fi

echo "== summary: moved=$moved skipped=$skipped apply=$APPLY =="
[[ $APPLY -eq 0 ]] && echo "(dry run — re-run with --apply after quiescing the daemon and runner)"
exit 0
