#!/usr/bin/env bash
# structural_2a.sh — the vault-side moves of filing-v2 part 2a, in one
# scripted, resumable pass.
#
# The code in this commit already writes to the new locations; this script
# moves the existing content to meet it. Run order on the live machine:
# merge the PR, update the clone, quiesce the daemon + runner, run with
# --apply, kickstart, verify. Until --apply is passed it only prints what it
# would do — the dry run IS the default, per the migration invariants
# (basenames preserved; dry-run reviewed before apply; link-check green on
# both sides).
#
# Idempotent: every move checks its source exists and its destination
# doesn't; a re-run after a partial apply completes the remainder and
# touches nothing done.
set -euo pipefail

VAULT="${MEMORY_VAULT_PATH:-}"
if [[ -z "$VAULT" || ! -d "$VAULT" ]]; then
  echo "structural_2a: MEMORY_VAULT_PATH unset or not a directory" >&2
  exit 2
fi

APPLY=0
[[ "${1:-}" == "--apply" ]] && APPLY=1

moved=0; skipped=0
say() { echo "  $*"; }
run() {
  if [[ $APPLY -eq 1 ]]; then "$@"; else say "would: $*"; fi
}

move_into() { # move_into <src-file-or-glob-expanded path> <dest-dir>
  local src="$1" dest="$2"
  [[ -e "$src" ]] || { skipped=$((skipped+1)); return 0; }
  local base e; base="$(basename "$src")"
  if [[ -d "$src" && -d "$dest/$base" && ! -L "$src" && ! -L "$dest/$base" ]]; then
    # Both sides are directories: `mv -f` would NEST the vault dir inside
    # the destination one, burying the production copy where no reader
    # looks. Merge per-entry instead — vault-wins at the file level — then
    # drop the emptied shell.
    say "merge (both directories): $base"
    for e in "$src"/*; do move_into "$e" "$dest/$base"; done
    [[ $APPLY -eq 1 ]] && rmdir "$src" 2>/dev/null || true
    return 0
  fi
  if [[ -e "$dest/$base" || -L "$dest/$base" ]]; then
    # Vault wins collisions: the script's precondition is a quiesced daemon
    # and runner, so the vault copy is the last production write. Anything
    # already at the destination predates the migration (typically scratch
    # leakage from verify runs) — and the engine dir's git history keeps it.
    say "collision: vault copy replaces destination copy: $base"
    if [[ ! -f "$src" || ! -f "$dest/$base" ]]; then
      # Mixed types (file over dir, dir over file): mv -f cannot replace —
      # clear the destination first, still vault-wins.
      run rm -rf "$dest/$base"
    fi
  fi
  run mv -f "$src" "$dest/$base"
  moved=$((moved+1))
}

echo "== task 2: diagnostics assembly =="
DIAG="$VAULT/diagnostics"
run mkdir -p "$DIAG/health" "$DIAG/dreaming" "$DIAG/digests"

OLD_DIAG="$VAULT/desk/diagnostics"
if [[ -d "$OLD_DIAG" ]]; then
  for f in "$OLD_DIAG"/*dreaming*; do move_into "$f" "$DIAG/dreaming"; done
  for f in "$OLD_DIAG"/*; do
    local_base="$(basename "$f")"
    [[ "$local_base" == "Icon"* ]] && continue   # Drive artifact, stays for the sync layer to manage
    [[ "$local_base" == *dreaming* ]] && continue # first loop's — keeps the dry run truthful
    move_into "$f" "$DIAG/health"
  done
  if [[ $APPLY -eq 1 ]]; then rmdir "$OLD_DIAG" 2>/dev/null || say "note: $OLD_DIAG not empty, left in place"; fi
fi

OLD_BRIEFS="$VAULT/desk/briefs"
if [[ -d "$OLD_BRIEFS" ]]; then
  for f in "$OLD_BRIEFS"/*; do
    [[ "$(basename "$f")" == "Icon"* ]] && continue
    move_into "$f" "$DIAG/digests"
  done
  if [[ $APPLY -eq 1 ]]; then rmdir "$OLD_BRIEFS" 2>/dev/null || say "note: $OLD_BRIEFS not empty, left in place"; fi
fi

MOC="$DIAG/moc-diagnostics.md"
if [[ ! -e "$MOC" && $APPLY -eq 1 ]]; then
  cat > "$MOC" <<'EOF'
---
title: moc-diagnostics
kind: moc
status: active
created: 2026-09-02
---

# Diagnostics

The system's health surfaces, one subdirectory per family. Regenerated by the
dreaming cadence once part 6 lands; seeded by the 2a migration until then.

- [[latest_health_scorecard]] — the corpus scorecard, in `health/`, dated
  copies beside it with the completeness and retrieval-gate verdicts.
- `dreaming/` — the dreaming scorecards: what the nightly pass did and spent.
- `digests/` — the daily digests and window-park notes the runner delivers.
EOF
  echo "  seeded $MOC"
elif [[ ! -e "$MOC" ]]; then
  say "would: seed $MOC"
fi

echo "== task 5: the engine state dir — init, then the machine files =="
STATE="${AGENTM_STATE_DIR:-$HOME/.local/state/agentm}"
run mkdir -p "$STATE"
if [[ ! -d "$STATE/.git" ]]; then
  if [[ $APPLY -eq 1 ]]; then
    git -C "$STATE" init -q
    printf 'dream-runs/\nscratch-sweep-*/\n*.tar.gz\n' > "$STATE/.gitignore"
    git -C "$STATE" add -A && git -C "$STATE" commit -q -m "engine state: initialized by the 2a migration" 2>/dev/null || true
    say "initialized git repo at $STATE (durability = history, replacing the vault's)"
  else
    say "would: git init $STATE + seed .gitignore (dream-runs/, scratch sweeps, tarballs)"
  fi
fi

OLD_META="$VAULT/_meta"
if [[ -d "$OLD_META" ]]; then
  # Everything machine goes; the one carve-out stays: repos.json is owned by
  # the storage seam's final design and moves only with that design's own
  # amendment (see the repoint map).
  for f in "$OLD_META"/*; do
    base_f="$(basename "$f")"
    [[ "$base_f" == "Icon"* ]] && continue
    [[ "$base_f" == "repos.json" ]] && { say "carve-out stays: _meta/repos.json (storage-seam owned)"; continue; }
    if [[ "$base_f" == vault-lint-*.md || "$base_f" == notes-links-*.md ]]; then
      # Report history is operator diagnostics, not machine state — the same
      # landing reclassified the writers to diagnostics/lint; the archive
      # follows them, or the console reads "dark" over a history that exists.
      run mkdir -p "$VAULT/diagnostics/lint"
      move_into "$f" "$VAULT/diagnostics/lint"
      continue
    fi
    if [[ "$base_f" == "health" && -d "$f" ]]; then
      run mkdir -p "$STATE/health"
      for h in "$f"/*; do move_into "$h" "$STATE/health"; done
      [[ $APPLY -eq 1 ]] && rmdir "$f" 2>/dev/null || true
      continue
    fi
    move_into "$f" "$STATE"
  done
fi

echo "== task 5: dreaming staging + insights leave the vault =="
run mkdir -p "$STATE/crystallize-staging" "$STATE/dream-runs"
if [[ -d "$VAULT/_crystallize-staging" ]]; then
  for f in "$VAULT/_crystallize-staging"/*; do move_into "$f" "$STATE/crystallize-staging"; done
  [[ $APPLY -eq 1 ]] && rmdir "$VAULT/_crystallize-staging" 2>/dev/null || true
fi
if [[ -d "$VAULT/_dream" ]]; then
  run mkdir -p "$STATE/dream-insights"
  for f in "$VAULT/_dream"/*; do
    if [[ -d "$f" ]]; then
      for g in "$f"/*; do move_into "$g" "$STATE/dream-insights"; done
      [[ $APPLY -eq 1 ]] && rmdir "$f" 2>/dev/null || true
    else
      move_into "$f" "$STATE/dream-insights"
    fi
  done
  [[ $APPLY -eq 1 ]] && rmdir "$VAULT/_dream" 2>/dev/null || true
fi

echo "== task 5: the forward-learning sources whitelist becomes a standard =="
FL_SRC="$STATE/forward-learning-sources.json"   # after an applied _meta sweep
# In a dry run nothing has been swept yet — read the file where it still
# sits, or the dry run omits this hop entirely and reviews an untruthful
# final home for the whitelist.
[[ -e "$FL_SRC" ]] || FL_SRC="$VAULT/_meta/forward-learning-sources.json"
STANDARDS="$(dirname "$VAULT")/standards"
[[ -d "$STANDARDS" ]] || STANDARDS="$VAULT/standards"
if [[ -e "$FL_SRC" ]]; then
  # Creating the flat fallback is required, not courtesy: load_sources()
  # probes only <vault-parent>/standards and <vault>/standards — a whitelist
  # left in $STATE is silently empty to every consumer.
  run mkdir -p "$STANDARDS"
  move_into "$FL_SRC" "$STANDARDS"
fi

echo "== task 3: the scratch sweep — out of the vault, kept, unsynced =="
if [[ -d "$VAULT/desk/scratch" ]]; then
  SWEEP="$STATE/scratch-sweep-20260902"
  run mkdir -p "$SWEEP"
  if [[ $APPLY -eq 1 ]]; then
    # One directory move, not per-file: 2,324 files, structure preserved.
    for f in "$VAULT/desk/scratch"/*; do
      base_f="$(basename "$f")"
      [[ "$base_f" == "Icon"* ]] && continue
      if [[ -e "$f/proposals.json" ]]; then
        # A staged dream/inbox run, not scratch: confirm, revert, and
        # cleanup all address $STATE/dream-runs/<run-id> — swept into a
        # gitignored sweep folder it would exist but answer to nothing.
        mkdir -p "$STATE/dream-runs"
        move_into "$f" "$STATE/dream-runs"
        continue
      fi
      mv "$f" "$SWEEP/$base_f" && moved=$((moved+1))
    done
    rmdir "$VAULT/desk/scratch" 2>/dev/null || say "note: desk/scratch not empty, left in place"
  else
    n_scratch="$(find "$VAULT/desk/scratch" -name '*.md' 2>/dev/null | wc -l | tr -d ' ')"
    n_runs="$(find "$VAULT/desk/scratch" -maxdepth 2 -name proposals.json 2>/dev/null | wc -l | tr -d ' ')"
    [[ "$n_runs" != "0" ]] && say "would: route $n_runs staged run dir(s) to $STATE/dream-runs (confirm/revert address them there)"
    say "would: sweep $n_scratch scratch files to $SWEEP (gitignored, unsynced)"
  fi
fi

echo "== task 3: desk/tasks — the workbench convention =="
run mkdir -p "$VAULT/desk/tasks"

echo "== summary: moved=$moved skipped=$skipped apply=$APPLY =="
[[ $APPLY -eq 0 ]] && echo "(dry run — re-run with --apply after quiescing the daemon and runner)"
exit 0
