#!/usr/bin/env python3
"""week1_summarize_runs.py — collapse a campaign's scorecards into one committable file.

A raw scorecard is ~200KB, most of it `tool_call_log`: every query the agent
wrote and every path the tool returned. That detail is what `week1_rank_replay.py`
reads, and it is worth having on the machine that ran the experiment. It is not
worth carrying in git forever, once per run, for every parameter a campaign
tried — a twelve-run campaign commits 2.4MB to establish twelve numbers.

This keeps what a reader or a re-analysis actually needs: each run's
configuration, its integrity block, its overall and per-stratum scores, and
per-question outcomes at one line each. A twelve-run campaign lands around 60KB.

Raw scorecards stay on disk under `--work-dir` or wherever the run wrote them,
and can be regenerated by re-running. The summary is the durable artifact.

    python3 scripts/health/week1_summarize_runs.py \\
        --out scripts/health/results/week1/rank-penalty-replicates.json \\
        scripts/health/results/week1/frozen-*.json
"""
from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path


def summarize_one(path):
    d = json.loads(Path(path).read_text(encoding="utf-8"))
    return {
        "run": Path(path).stem,
        "arm": d["arm"],
        "driver": d.get("driver"),
        "model": d.get("model"),
        "lexical_variant": d.get("lexical_variant"),
        "query_mode": d.get("query_mode"),
        "penalty": d.get("penalty"),
        "call_budget": d["call_budget"],
        "n_questions": d["n_questions"],
        "corpus": d["corpus"],
        "vault_name": d.get("vault_name"),
        "gold_set": d.get("gold_set"),
        "cost_usd_total": d.get("cost_usd_total"),
        "wall_s_total": d.get("wall_s_total"),
        "overall": d["overall"],
        "per_stratum": d["per_stratum"],
        # The integrity block is the reason any of these numbers can be read at
        # all — a run with a hook violation measured something else entirely.
        # It stays, in full, at every size.
        "integrity": d["integrity"],
        # One line per question. Enough to recompute any aggregate in the
        # write-up, or to see which questions a configuration flipped.
        "per_question": [
            {"id": r["id"], "stratum": r["stratum"], "correct": r["correct"],
             "r_at_5": r["r_at_5"], "p_at_5": r["p_at_5"],
             "tool_calls": r["tool_calls"], "n_expected": len(r["expected"])}
            for r in d["per_question"]
        ],
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("reports", nargs="+")
    ap.add_argument("--out", required=True)
    ap.add_argument("--label", default=None, help="what this campaign measured")
    args = ap.parse_args(argv if argv is not None else sys.argv[1:])

    runs = [summarize_one(p) for p in sorted(args.reports)]
    by_config = {}
    for r in runs:
        key = "penalty" if r["penalty"] else "control"
        by_config.setdefault(key, []).append(r["overall"]["r_at_5"])
    arms = {}
    for key, vals in sorted(by_config.items()):
        arms[key] = {
            "n": len(vals),
            "mean_r_at_5": round(statistics.mean(vals), 4),
            "sd": round(statistics.stdev(vals), 4) if len(vals) > 1 else None,
            "min": min(vals), "max": max(vals), "values": vals,
        }

    out = {"label": args.label, "n_runs": len(runs), "arms": arms, "runs": runs}
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(json.dumps(out, indent=2), encoding="utf-8")
    size = Path(args.out).stat().st_size
    print(f"[summarize] {len(runs)} run(s) -> {args.out} ({size / 1024:.0f} KB)")
    for key, a in arms.items():
        sd = f" sd={a['sd']:.4f}" if a["sd"] is not None else ""
        print(f"  {key:<8} n={a['n']} mean={a['mean_r_at_5']:.4f}{sd} "
              f"range=[{a['min']:.3f}, {a['max']:.3f}]")
    return 0


if __name__ == "__main__":
    import sys
    raise SystemExit(main())
